Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/blog/urls.py
from django.views.generic import ListView, DetailView
from django.urls import path
from .models import Post

urlpatterns = [
    path('',
         ListView.as_view(
            queryset=Post.objects.all().order_by("-date")[:25],
            template_name="blog.html")),
    path('<int:pk>/',
         DetailView.as_view(model=Post, template_name="post.html")),
]

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/hyperion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_auth/', include("django.contrib.auth.urls")),
    path('accounts/login/', include("user_auth.urls")),
    path('webapp/', include('webapp.urls')),
    path('blog/', include('blog.urls')),
    path('', include('polls.urls'))
]

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/user_auth/urls.py
from django.urls import path
from . import views

app_name = 'user_auth'
urlpatterns = [
    path('', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user,
         name='authenticate_user'),
    path("signup/", views.SignUpView, name="signup")
]

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/webapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
]

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/blog/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    # Manually setting the primary key
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=140)
    body = models.TextField()
    signature = models.CharField(max_length=140, default="HyperionDev Student")
    date = models.DateTimeField()


def __str__(self):
    return self.title

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/polls/models.py
from django.db import models


# Create your models here.
class Question(models.Model):
    '''This class defines the data types
    for question_text and pub_date'''
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        '''Returns the question text'''
        return self.question_text


class Choice(models.Model):
    '''This class defines the data types
    for question, choice_text and votes'''
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        '''Returns the choice text'''
        return self.choice_text

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/user_auth/models.py
from django.db import models

# Create your models here.

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/webapp/models.py
from django.db import models

# Create your models here.

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/blog/views.py
from django.shortcuts import render

# Create your views here.

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Question, Choice
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    '''Renders the poll.html'''
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, "polls/poll.html", context)


def detail(request, question_id):
    '''Renders the detail.html'''
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(
            pk=request.POST['choice']
        )
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    # Always return an HttpResponseRedirect after successfully
    # dealing with POST data. This prevents data from being
    # posted twice if a user hits the Back button.
    return HttpResponseRedirect(
        reverse('polls:results', args=(question_id,))
    )

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/user_auth/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm


def SignUpView(request):
    '''Gets the UserCreationFrom for the
    registration of new users'''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('user_auth:login')
    else:
        form = UserCreationForm()
        return render(request, 'authentication/signup.html',
                      {'form': form})


# Create your views here.
def user_login(request):
    '''Renders the login.html'''
    return render(request, 'authentication/login.html')


def authenticate_user(request):
    '''Authenticates the user
    Gets the username and password from the form
    and does an authenticate check.'''
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
            reverse('user_auth:login'))
    else:
        login(request, user)
        return HttpResponseRedirect(
            reverse('polls:index'))

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/webapp/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, "index.html")

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
    <head>
        <title>Poll Details:</title>
            <!--CSS ONLY-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
<body>
    <div class="container">
        <header>
            <h1> {{question.question_text}}</h1>
        </header>
        <div class="row">
            <div class="col-md-4">
                {% if error_message %}
                <p><strong>{{error_message}}</strong></p>
                {% endif %}

                <form action="{% url 'polls:vote' question.id %}" method="post">
                    {% csrf_token %}

                    {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice {{
                        forloop.counter
                    }}" value="{{ choice.id }}" />
                    <label for="choice {{ forloop.counter }}">
                        {{ choice.choice_text }}
                    </label>
                    <br />
                    {% endfor %}
                    
                    <input type="submit" value="Vote" />
                </form>
            </div>
        </div>
        <br>
        <!--Navigation link-->
        <a href="/">Back</a>
    </div>
</body>
</html>

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/polls/templates/polls/poll.html
<!DOCTYPE html>
<html>
    <head>
        <title>Poll Questions</title>
        <!--CSS ONLY-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
<body>
    <div class="container">
        <header>
            <h1>Poll Questions:</h1>
        </header>
        <div class="row">
            <div class="col-md-4">
                {% if latest_question_list %}
                <ul>
                    {% for question in latest_question_list %}
                    <li>
                        <a href = "{% url 'polls:detail' question.id %}">
                            {{ question.question_text }}
                        </a>
                    </li>
                    {% endfor %}
                    {% else %}
                    <p>No polls are available.</p>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</body>
</html>

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/polls/templates/polls/results.html
<!DOCTYPE html>
<html>
    <head>
        <title>Poll results:</title>
            <!--CSS ONLY-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
<body>
    <div class="container">
        <header>
            <h1> {{question.question_text}}</h1>
        </header>
        <div class="row">
            <div class="col-md-4">
                <ul>
                    {% for choice in question.choice_set.all %}
                    <li>
                        {{ choice.choice_text }} -- {{ choice.votes}}
                        vote{{choice.votes|pluralize}}
                    </li>
                    {% endfor %}
                </ul>

                <a href="{% url 'polls:detail' question.id %}">
                    Vote again?
                </a>
            </div>
        </div>
        <br>
        <!--Navigation link-->
        <a href="/">Back</a>
    </div>
</body>
</html>

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/user_auth/templates/authentication/login.html
<h1> Please login </h1>

<form action="{% url 'user_auth:authenticate_user' %}" method="post">
    {% csrf_token %}
    
    <label>Username</label>
    <input type="text" name="username" required>
    <br/><br/>

    <label>Password</label>
    <input type="password" name="password" required>
    <br/><br/>

    <input type="submit" value="Login" />
    <!--Link for user registration-->
    <p>Don't have an account? <a href="{% url 'user_auth:signup' %}"
        class="text-primary fw-bold">Sign Up</a></p>
</form>

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/user_auth/templates/authentication/signup.html
{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
  </form>
{% endblock %}

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/user_auth/templates/authentication/user.html
<h1> Welcome, {{username}} </h1>

<p> Your password is {{password}}</p>

Level 2/L2T22 - Django - Poll App and Authentication/Tasks/hyperion/webapp/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Heinrich Bester - Online CV</title>
    <link href="{% static 'assets/externalCSS.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
    <section class="mainbody">
        <h1>Heinrich Bester</h1>
        <!--Random stock photo-->
        <img src="{% static 'assets/stock photo.webp' %}" alt="Stock Image of a profile picture">
        <section>
        <!--Short bio-->
            <p>As a kid, I always liked puzzles and strategy games Starcraft, Command & Conquer and
                Age Of Empires. Then, I got introduced to programming via friends, and school and
                instantly liked the idea and enjoyed it. It feels like solving a puzzle to get the
                desired results or outcome. Finding the answer or fixing what is broken usually
                gives me more motivation. I would like to either be a software developer, software
                engineer or even a game developer the things I would like to do the most and
                possibly live in Japan in the future, their food is awesome and the culture
                is interesting.</p>
        </section>
        <hr size="1" width="100%" color="black">
        <!--Lists the skills & competencies, education and work experience.-->
        <section>
            <h3><u>Skills & Competencies:</u></h3>
            <ul>
                <li>ISTQB® Certified Tester Foundation Level - July 2018</li>
                <li>API & Web Service Introduction - December 2020</li>
                <li>Quick Introduction to Postman for Beginners - December 2020</li>
                <li>Postman : The Complete Guide – REST API Testing - March 2021</li>
            </ul>
            <h3><u>Education:</u></h3>
            <ul>
                <li>Highschool Gimnasium, Potchefstroom (Matric December 2011)</li>
                <li>College: CTI (Potchefstroom & Durban) Comprehensive Programming - February 2014</li>
            </ul>
            <h3><u>Current Courses:</u></h3>
            <ul>
                <li>HyperionDev Software engineering bootcamp.</li>
            </ul>
            <h3><u>Work experience:</u></h3>
            <ul>
                <li>I have no official work experience.</li>
            </ul>
            <!--Contact Information.-->
            <h3><u>Contact Details:</u></h3>
            <p>Name : Heinrich Bester</p>
            <p>Phone number: 0815593777</p>
            <p>Email Address: heinrichbester@gmail.com</p>
            <p><a href="https://www.linkedin.com/in/heinrich-bester-2b0342169" target="_blank">LinkedIn</a></p>
			<p><a href="/blog/">Blog</a></p>
            <hr size="1" width="100%" color="black">
        </section>
        <section>
            <!--Form for searching information of the CV content-->
            <h3>CV Search</h3>
            <form id="cvSearch" action="" method="get">
                <label for="search">Search:</label>
                <input type="text" id="search" name="search" placeholder="Enter keywords to search">
                <button type="submit">Search</button>
            </form>
            <!--Forms for people to reach out or leave comments-->
            <h3>Contact Form</h3>
            <form id="contactForm">
                <label for="name">Name:</label>
                <input type="text" id="name" name="name" required> <br>
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required> <br>
                <label for="message">Message:</label> <br>
                <textarea id="message" name="message" rows="5" required></textarea> <br>
                <input type="submit" value="Send Message">
            </form>
        </section>
    </section>      
</body>
</html>